### ISSUE TITLE
Completions not working

### ISSUE THREAD

**Issue by xbb** [Zsh-Packages/fzf#5]
I installed the "bgn-binary+keys" and "bgn-binary" packages however the completions are not working unless I manually source the file `~/.zinit/completions/_fzf_completion`

Am I missing something?

Thanks

**Comment by xbb** [comment]
Solved with this: https://github.com/Zsh-Packages/fzf/issues/8#issuecomment-815641464

**Comment by ChampiYann** [comment]
Completion is still not working here when using pack.
Adding OMZP::fzf doesn't work either.
